baseurl: "/"
permalink: pretty
title: "Pete Davis"
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  indentWidth: 4
  style: compact
  precision: 10

google_analytics_id: false # replace with "UA-XXXX"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

logo:
  logo_desktop_image: assets/images/logo/logo.svg
  logo_desktop_text: "Pete <strong>Davis</strong>"
  logo_mobile_image: assets/images/logo/logo-mobile.svg
  logo_mobile_text: ""
  logo_desktop_height: "36px"
  logo_desktop_width: "36px"
  logo_mobile_height: "36px"
  logo_mobile_width: "36px"

seo:
  meta_twitter_site: "@pete_davis"
  meta_twitter_creator: "@zerostaticio"
  meta_og_image: "https://www.zerostatic.io/theme/jekyll-atlantic/jekyll-atlantic-screenshot.png"

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-paginate

paginate: 3
paginate_path: /blog/page:num/

collections:
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      layout: category
      permalink: /category/:basename/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
